spring.application.name=category
spring.datasource.url=jdbc:mysql://localhost:3306/dwb2026_1
spring.datasource.username=root
spring.datasource.password=saritabb7u7
spring.datasource.driverClassName=com.mysql.jdbc.Driver

